In [ ]:
import numpy as np

In [1]:
pattern_base = np.zeros(12)
pattern_base

NameError: name 'np' is not defined

In [12]:
pressure_values = np.linspace(0, 30, 7)
#for trial in range(10): # number of trials -> repeat this many times
pressure_values

array([ 0.,  5., 10., 15., 20., 25., 30.])

In [15]:
index_of_actuator = 1
pattern = []
for trial in range(10): # number of trials -> repeat this many times
    for val in pressure_values:
        for i in range(2): # index of the actuator
            pattern_base = np.zeros(12)
            pattern_base[11] = 10
            pattern_base[2*index_of_actuator + i] = val
            pattern.append(pattern_base)

In [16]:
pattern

[array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0., 15.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0., 15.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0., 20.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0., 20.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0., 25.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0., 25.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0., 30.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0., 30.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0

In [19]:
pressure_values = np.linspace(0, 30, 31)
pressure_values_2 = pressure_values[::-1]
pressure_values = np.append(pressure_values, pressure_values_2)
pressure_values

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 30., 29., 28., 27., 26., 25., 24., 23.,
       22., 21., 20., 19., 18., 17., 16., 15., 14., 13., 12., 11., 10.,
        9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0.])

In [22]:

pattern = []
for trial in range(10): # number of trials -> repeat this many times
    for index in range(4):
        for i in range(2): # index of the actuator
            for val in pressure_values:
                pattern_base = np.zeros(12)
                pattern_base[11] = 10
                pattern_base[2*index + i] = val
                pattern.append(pattern_base)

In [23]:
pattern

[array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 6.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 7.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([11.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([12.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([13.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([14.,  0.,  0

In [ ]:
actuator_pattern = [-25, 0, 25, 0]
pattern = np.array([])
for val in actuator_pattern:
    regulator_vals = np.zeros(12)
    if val < 0:
        regulator_vals[2 * index_of_actuator + 1] = abs(val)
    else:
        regulator_vals[2 * index_of_actuator] = abs(val)
    
    pattern = np.append(pattern, list(regulator_vals))

print(pattern)

In [6]:
def generate_pattern_1(start, end, inc):
    result = list(np.arange(start, end + inc, inc)) + list(np.arange(end - inc, start - inc))
    return np.array(result)

In [10]:
actuator_pattern = generate_pattern_1(-25, 25, 0.5)
actuator_pattern

array([-25. , -24.5, -24. , -23.5, -23. , -22.5, -22. , -21.5, -21. ,
       -20.5, -20. , -19.5, -19. , -18.5, -18. , -17.5, -17. , -16.5,
       -16. , -15.5, -15. , -14.5, -14. , -13.5, -13. , -12.5, -12. ,
       -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,
        -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,
        -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,
         2. ,   2.5,   3. ,   3.5,   4. ,   4.5,   5. ,   5.5,   6. ,
         6.5,   7. ,   7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5,
        11. ,  11.5,  12. ,  12.5,  13. ,  13.5,  14. ,  14.5,  15. ,
        15.5,  16. ,  16.5,  17. ,  17.5,  18. ,  18.5,  19. ,  19.5,
        20. ,  20.5,  21. ,  21.5,  22. ,  22.5,  23. ,  23.5,  24. ,
        24.5,  25. ])

In [8]:
import numpy as np