In [1]:
import numpy as np

In [3]:
pattern_base = np.zeros(12)
pattern_base

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
pressure_values = np.linspace(0, 30, 7)
#for trial in range(10): # number of trials -> repeat this many times
pressure_values

array([ 0.,  5., 10., 15., 20., 25., 30.])

In [15]:
index_of_actuator = 1
pattern = []
for trial in range(10): # number of trials -> repeat this many times
    for val in pressure_values:
        for i in range(2): # index of the actuator
            pattern_base = np.zeros(12)
            pattern_base[11] = 10
            pattern_base[2*index_of_actuator + i] = val
            pattern.append(pattern_base)

In [16]:
pattern

[array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0., 15.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0., 15.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0., 20.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0., 20.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0., 25.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0., 25.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0., 30.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0., 30.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 0.,  0.,  0

In [19]:
pressure_values = np.linspace(0, 30, 31)
pressure_values_2 = pressure_values[::-1]
pressure_values = np.append(pressure_values, pressure_values_2)
pressure_values

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 30., 29., 28., 27., 26., 25., 24., 23.,
       22., 21., 20., 19., 18., 17., 16., 15., 14., 13., 12., 11., 10.,
        9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0.])

In [22]:

pattern = []
for trial in range(10): # number of trials -> repeat this many times
    for index in range(4):
        for i in range(2): # index of the actuator
            for val in pressure_values:
                pattern_base = np.zeros(12)
                pattern_base[11] = 10
                pattern_base[2*index + i] = val
                pattern.append(pattern_base)

In [23]:
pattern

[array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 6.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 7.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([ 9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([11.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([12.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([13.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]),
 array([14.,  0.,  0